use_cuda: true
add_self_loops: false
agent_package: 100
chunk_size: 64
diff_or: true
dropout_rate: 0
dropout_rate2: 0
train_valid_split: true
train_valid_split_rate:
- 0.8
- 0.2
epochs: 2000
full_batch: false
batch_size: 2048
global_gating: false
in_channel: 256
hidden_channel: 256
out_channel: 256
index_split:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
learning_rate: 0.0001
log_freq: 200
model: ONGNN
num_layers: 8
num_layers_input: 2
patience: 200
save_model: false
seed: 42
simple_gating: false
# task: Actor
data_path: dataset/movielens100k
tm: true
weight_decay: 0.0005
weight_decay2: 0.05
