use_cuda: true
add_self_loops: false
agent_package: 100
chunk_size: 64
diff_or: true
dropout_rate: 0
dropout_rate2: 0
train_valid_split: true
train_valid_split_rate:
- 0.8
- 0.2
epochs: 512
print_every: 1
full_batch: false
batch_size: 2048
global_gating: false
in_channel: 64
hidden_channel: 64
out_channel: 64
index_split:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
learning_rate: 0.0005
log_freq: 200
model: ONGNN
num_layers: 6
num_layers_input: 2
# early stop
do_early_stop: true
early_stop_policy: ndcg #loss, recall, precision, ndcg
early_stop_threshold: 5
#
save_model: false
seed: 42
simple_gating: false
# task: Actor
data_path: dataset/yelp2018
tm: true
weight_decay: 0.0005
weight_decay2: 0.05
